version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub